[package]
name = "parts"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"

[dependencies]
uuid = { version = "0.7.4", features = ["v1"] }
serde = { version = "1.0.101", features = ["derive"] }
bincode = "1.1.4"
crc = "1.8.1"

[dependencies.snafu]
version = "0.5.0"
default-features = false
features = [
    "rust_1_30",
]
