[package]
name = "parts"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"
#
publish = false
license = "MIT OR Apache-2.0"
#
description = "A GPT Partition Manager"

[dependencies]
uuid = { version = "0.8.1", features = ["v4", "serde"] }
serde = { version = "1.0.104", features = ["derive"] }
bincode = "1.2.1"
crc = "1.8.1"
generic-array = { version = "0.13.2", features = ["serde"] }
derive_more = "0.99.3"
thiserror = "1.0.11"
displaydoc = "0.1.5"

[dev-dependencies]
static_assertions = "1.1.0"
anyhow = "1.0.26"

[target.'cfg(fuzzing)'.dependencies]
honggfuzz = "0.5.46"

[features]
# Nightly is used for docs.
nightly = []

[package.metadata.docs.rs]
features = [
    "nightly",
]
