[package]
name = "parts"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"
#
publish = false
license = "MIT OR Apache-2.0"
#
description = "A GPT Partition Manager"

[dependencies]
uuid = { version = "0.8.1", default-features = false, features = ["v4", "v1"] }
crc = { version = "1.8.1", default-features = false }
generic-array = "0.13.2"
derive_more = "0.99.3"
displaydoc = { version = "0.1.5", default-features = false }
thiserror = { version = "1.0.11", optional = true }

[dev-dependencies]
static_assertions = "1.1.0"
anyhow = "1.0.26"
thiserror = "1.0.11"

[target.'cfg(fuzzing)'.dependencies]
honggfuzz = "0.5.47"

[features]
# Enable support for various standard library types
std = [
    "thiserror"
]
# Nightly is used for docs.
nightly = []

[package.metadata.docs.rs]
features = [
    "nightly",
]
