[package]
name = "parts"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"

[dependencies]
uuid = { version = "0.7.4", features = ["v4", "serde"] }
serde = { version = "1.0.101", features = ["derive"] }
bincode = "1.2.0"
crc = "1.8.1"
generic-array = { version = "0.13.2", features = ["serde"] }

[dependencies.snafu]
version = "0.5.0"
default-features = false
features = [
    "rust_1_30",
]

[dev-dependencies]
static_assertions = "0.3.4"
prettydiff = "0.3.1"

[target.'cfg(fuzzing)'.dependencies]
honggfuzz = "0.5"
